---
debug: False
datalogger:
  host:
  port: 502
  slave_id: 1
  poll_interval: 60
  poll_interval_if_off: 600
  poll_retries: 10
  register_chunks: 20
  http:
    enabled: True
    user: admin
    password: "123456789"
inverter:
  name: Solis
  manufacturer: Ginlong Technologies
  model: S5-GR3P15K
mqtt:
  enabled: True
  host:
  port: 1883
  topic_prefix: tcpsolis2mqtt
  client_id: tcpsolis2mqtt
  user:
  password:
  use_ssl: False
  validate_cert: False
